language: node_js
node_js:
  - 12
branches:
jobs:
  include:
    - stage: install
      script: npm install
      skip_cleanup: true
    - stage: test
      script:
        - npm run lint
        - npm run pre:test
        - npm test
      after_success:
        - npx codecov
      skip_cleanup: true
    - stage: Build & publish
      script:
        - npm run build
        - npx semantic-release
      if: branch = master
